version: "3.8"

services:
#  server:
#    build: ./Server
#    ports:
#      - "8000:8000"
#    container_name: ride-server

  web:
    build: ./Web
    ports:
      - "3000:3000"
    container_name: ride-web

  android:
    build:
      context: .
      dockerfile: Docker/android.Dockerfile
    volumes:
      - .:/workspace
    container_name: ride-android
